<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\images\hero\" />
    <Folder Include="wwwroot\images\products\new-arrivals\" />
    <Folder Include="wwwroot\images\products\men\" />
    <Folder Include="wwwroot\images\products\kurti\" />
    <Folder Include="wwwroot\images\products\accessories\" />
    <Folder Include="wwwroot\images\products\makeup\" />
    <Folder Include="wwwroot\images\products\offers\" />
    <Folder Include="wwwroot\images\products\skincare\" />
    <Folder Include="wwwroot\images\products\saree\" />
    <Folder Include="wwwroot\images\products\women\" />
  </ItemGroup>

</Project>
